#!/usr/bin/env python3
"""
Database Seed Script — Ticket Management System
================================================
Clears all data and generates a fresh multi-tenant test dataset.

Usage:
    pip install pymysql          # first time only
    python seed_db.py            # uses defaults below
    python seed_db.py --help     # see all options

Configuration — modify the CONFIG dict below, or override via CLI args.
"""

import argparse
import sys
import time
import random
import textwrap

# ═══════════════════════════════════════════════════════════════════
#  CONFIGURATION (override with CLI flags: --tenants 5 --agents 3 ...)
# ═══════════════════════════════════════════════════════════════════
CONFIG = {
    "host": "127.0.0.1",
    "port": 3306,
    "user": "root",
    "password": "jw-0505",
    "database": "ticket_db",  # <-- change to your actual DB name
    "num_tenants": 3,             # how many tenants to create
    "agents_per_tenant": 4,       # agents per tenant (not counting admin)
    "users_per_tenant": 8,        # regular users per tenant
    "tickets_per_tenant": 10000,     # tickets to generate per tenant
}
# ═══════════════════════════════════════════════════════════════════

# Pre-computed BCrypt hashes (cost=10, matching Spring Security defaults)
# These were generated by the app's UserServiceImpl — use them as-is.
BCRYPT = {
    "admin@123": "$2b$10$PAoQ1fY8qFNLysbwyfl74e9RTwgm9N2H8s0vSNXqnCbmb3y4wIMKi",
    "agent@123": "$2b$10$JUAd5ZVNbT.DMuEACW60KewCOZJRGDvHgbzdeJpTU8YCEEZkNaywy",
    "user@123":  "$2b$10$N4t9sIbuMa2ALsqFTx8CPuYuvXDGihCfeoDXW3li7f8WRKSKAydiK",
}

NOW_MS = int(time.time() * 1000)

# Ticket categories & priorities for random generation
CATEGORIES = ["BUG", "FEATURE_REQUEST", "GENERAL_QUESTION", "ACCOUNT_ISSUE", "OTHER"]
PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"]
STATUSES = ["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]

# ── Helpers ────────────────────────────────────────────────────────

def ts(offset_seconds=0):
    """Epoch millis timestamp, optionally offset from now."""
    return NOW_MS + offset_seconds * 1000

def insert(cursor, table, **kwargs):
    """Construct & execute INSERT INTO table (cols) VALUES (%s...)"""
    cols = list(kwargs.keys())
    placeholders = ", ".join(["%s"] * len(cols))
    values = list(kwargs.values())
    col_names = ", ".join(cols)
    sql = f"INSERT INTO {table} ({col_names}) VALUES ({placeholders})"
    cursor.execute(sql, values)
    return cursor.lastrowid

def clear_all(cursor):
    """Truncate all tables in FK-safe order (children first)."""
    tables = [
        "survey_answer",
        "survey_instance_page",
        "survey_instance",
        "survey_visibility_rule",
        "survey_question",
        "survey_section",
        "survey_page",
        "survey_template",
        "notification",
        "ticket_attachment",
        "ticket_reply",
        "ticket",
        "sla_config",
        "ticket_field_config",
        "knowledge_article",
        "reply_template",
        "audit_log",
        "invite_token",
        "user",
        "tenant",
    ]
    cursor.execute("SET FOREIGN_KEY_CHECKS = 0")
    for t in tables:
        cursor.execute(f"TRUNCATE TABLE {t}")

    # Ensure tenant_id columns allow NULL (superadmin / system defaults use NULL)
    cursor.execute("ALTER TABLE user MODIFY tenant_id BIGINT NULL")
    cursor.execute("ALTER TABLE survey_template MODIFY tenant_id BIGINT NULL")
    cursor.execute("ALTER TABLE sla_config MODIFY tenant_id BIGINT NULL")
    print(f"  ✓ Truncated {len(tables)} tables + ensured tenant_id allows NULL")

    cursor.execute("SET FOREIGN_KEY_CHECKS = 1")

# ── Tenants ────────────────────────────────────────────────────────

def create_tenants(cursor, n):
    """Create n tenants, return list of tenant ids."""
    ids = []
    for i in range(1, n + 1):
        tid = insert(cursor, "tenant",
                     name=f"Tenant {i:02d}",
                     slug=f"tenant-{i:02d}",
                     status=1,
                     created_date=ts())
        ids.append(tid)
    print(f"  ✓ Created {n} tenant(s)")
    return ids

# ── Users ──────────────────────────────────────────────────────────

def create_superadmin(cursor):
    """Superadmin: tenant_id=NULL, role=ROLE_ADMIN."""
    uid = insert(cursor, "user",
                 tenant_id=None,
                 username="superadmin",
                 email="superadmin@system.local",
                 password=BCRYPT["admin@123"],
                 role="ROLE_ADMIN",
                 status=1,
                 created_by=0,
                 created_date=ts())
    print(f"  ✓ Superadmin created (id={uid}, tenant_id=NULL)")
    return uid

def create_users_for_tenant(cursor, tenant_id, tenant_label, num_agents, num_users):
    """
    Create users for one tenant:
      - 1 admin:  admin{tenant_id}  (ROLE_ADMIN)
      - N agents: agent{tenant_id}-{n}  (ROLE_AGENT)
      - K users:  user{tenant_id}-{n}   (ROLE_USER)
    Returns { 'admin': id, 'agents': [ids], 'users': [ids] }
    """
    now = ts()
    # Admin
    admin_id = insert(cursor, "user",
                      tenant_id=tenant_id,
                      username=f"admin{tenant_id}",
                      email=f"admin{tenant_id}@tenant-{tenant_label}.local",
                      password=BCRYPT["admin@123"],
                      role="ROLE_ADMIN",
                      status=1,
                      created_by=0,
                      created_date=now)

    # Agents
    agent_ids = []
    for j in range(1, num_agents + 1):
        aid = insert(cursor, "user",
                     tenant_id=tenant_id,
                     username=f"agent{tenant_id}-{j}",
                     email=f"agent{tenant_id}-{j}@tenant-{tenant_label}.local",
                     password=BCRYPT["agent@123"],
                     role="ROLE_AGENT",
                     status=1,
                     created_by=admin_id,
                     created_date=now + j * 1000)
        agent_ids.append(aid)

    # Users
    user_ids = []
    for k in range(1, num_users + 1):
        uid = insert(cursor, "user",
                     tenant_id=tenant_id,
                     username=f"user{tenant_id}-{k}",
                     email=f"user{tenant_id}-{k}@tenant-{tenant_label}.local",
                     password=BCRYPT["user@123"],
                     role="ROLE_USER",
                     status=1,
                     created_by=admin_id,
                     created_date=now + (num_agents + k) * 1000)
        user_ids.append(uid)

    return {"admin": admin_id, "agents": agent_ids, "users": user_ids}

# ── System Default Configs (under superadmin) ──────────────────────

def create_reply_templates(cursor, superadmin_id):
    """Pre-seeded reply templates (same as Flyway V2 seed)."""
    templates = [
        ("Request Screenshot", "Could you please provide a screenshot of the issue? This will help us diagnose the problem more quickly.", "TROUBLESHOOTING"),
        ("Investigating", "We are currently investigating your issue and will update you shortly. Thank you for your patience.", "STATUS_UPDATE"),
        ("Resolution Confirmed", "The issue has been resolved. Please verify the fix on your end and let us know if you have any further questions.", "RESOLVED"),
        ("Need More Information", "To proceed, we need additional details:\n\n1. Steps to reproduce\n2. Environment (browser/OS)\n3. Exact error message\n\nPlease reply with this information.", "TROUBLESHOOTING"),
        ("Escalate to Dev Team", "This issue has been escalated to our development team for further investigation. You will be notified when there is an update.", "ESCALATION"),
    ]
    for title, content, category in templates:
        insert(cursor, "reply_template",
               tenant_id=None,
               title=title,
               content=content,
               category=category,
               created_by=superadmin_id,
               created_date=ts())
    print(f"  ✓ Created {len(templates)} reply templates")

def create_knowledge_articles(cursor, superadmin_id):
    """Pre-seeded knowledge base articles."""
    articles = [
        ("How to Reset Your Password",
         "## Password Reset Guide\n\n"
         "1. Go to **Settings** > **Change Password**\n"
         "2. Enter your current password\n"
         "3. Enter and confirm your new password (minimum 8 characters, must include uppercase, lowercase, and a number)\n"
         "4. Click **Update Password**\n\n"
         "> **Note:** If you have forgotten your current password, please contact your administrator.",
         "ACCOUNT"),
        ("How to Submit a Ticket",
         "## Submitting a Ticket\n\n"
         "1. Click **New Ticket** in the sidebar\n"
         "2. Fill in the **Title** (be specific — e.g., \"Login page returns 500 error\")\n"
         "3. Choose the appropriate **Category** and **Priority**\n"
         "4. Describe the issue in detail, including steps to reproduce\n"
         "5. Attach any relevant screenshots or log files\n"
         "6. Click **Submit**\n\n"
         "Your ticket will be assigned to an agent who will follow up shortly.",
         "GENERAL"),
        ("Understanding Ticket Priorities",
         "## Priority Levels\n\n"
         "| Priority | Response SLA | Resolution SLA | Examples |\n"
         "|----------|-------------|----------------|----------|\n"
         "| **URGENT** | 1 hour | 4 hours | Production outage, security breach |\n"
         "| **HIGH** | 4 hours | 24 hours | Critical feature broken, major blocker |\n"
         "| **MEDIUM** | 8 hours | 48 hours | Non-critical issue, workaround exists |\n"
         "| **LOW** | 24 hours | 96 hours | Cosmetic issue, feature request |\n\n"
         "Choose the priority that best matches the business impact of your issue.",
         "GENERAL"),
        ("Troubleshooting Common Login Issues",
         "## Login Troubleshooting\n\n"
         "### \"Invalid credentials\"\n"
         "- Verify your username/email is typed correctly\n"
         "- Check that Caps Lock is off\n"
         "- Try resetting your password\n\n"
         "### \"Account disabled\"\n"
         "- Your account may have been deactivated — contact your administrator\n\n"
         "### \"Too many attempts\"\n"
         "- Wait 15 minutes before trying again\n"
         "- Use the \"Forgot Password\" link if needed",
         "TROUBLESHOOTING"),
    ]
    for title, content, category in articles:
        insert(cursor, "knowledge_article",
               tenant_id=None,
               title=title,
               content=content,
               category=category,
               tags="",
               view_count=random.randint(10, 500),
               created_by=superadmin_id,
               created_date=ts())
    print(f"  ✓ Created {len(articles)} knowledge base articles")

def create_sla_configs(cursor, superadmin_id, tenant_ids):
    """System-wide SLA defaults (tenant_id=NULL). Per-tenant overrides created on-demand via copy-on-write."""
    slas = [
        ("URGENT", 60, 240),
        ("HIGH",   240, 1440),
        ("MEDIUM", 480, 2880),
        ("LOW",    1440, 5760),
    ]
    for priority, resp, reso in slas:
        insert(cursor, "sla_config",
               tenant_id=None,
               priority=priority,
               response_minutes=resp,
               resolution_minutes=reso,
               active=1,
               created_by=superadmin_id,
               created_date=ts())
    print(f"  ✓ Created {len(slas)} system SLA configs (tenant_id=NULL, inherited by all tenants)")

def create_survey_templates(cursor, superadmin_id):
    """
    Create 2 system survey templates under superadmin.
    Each with pages, sections, and mixed question types.
    """
    template_ids = []
    now = ts()

    # ── Template 1: Customer Satisfaction Survey ──
    t1 = insert(cursor, "survey_template",
                tenant_id=None,
                title="Customer Satisfaction Survey",
                description="Help us improve our service by sharing your feedback.",
                status="PUBLISHED",
                version=1,
                allow_resubmit=0,
                created_by=superadmin_id,
                created_date=now,
                last_modified_date=now)
    template_ids.append(t1)

    # Page 1: Overall Experience
    p1 = insert(cursor, "survey_page", template_id=t1, title="Overall Experience",
                display_order=0, created_by=superadmin_id, created_date=now)
    # Section 1.1
    s11 = insert(cursor, "survey_section", page_id=p1, title="Service Rating",
                 display_order=0, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s11, type="RATING", title="How would you rate our overall service?",
           options='{"max":5}', required=1, display_order=0, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s11, type="SINGLE_CHOICE",
           title="How did you hear about us?",
           options='{"options":[{"key":"search","label":"Search Engine"},{"key":"friend","label":"Friend Referral"},{"key":"social","label":"Social Media"},{"key":"ad","label":"Advertisement"},{"key":"other","label":"Other"}]}',
           required=0, display_order=1, created_by=superadmin_id, created_date=now)
    # Section 1.2
    s12 = insert(cursor, "survey_section", page_id=p1, title="Comments",
                 display_order=1, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s12, type="TEXTAREA",
           title="What can we do to improve your experience?",
           options=None, required=0, display_order=0, created_by=superadmin_id, created_date=now)

    # Page 2: Product Feedback
    p2 = insert(cursor, "survey_page", template_id=t1, title="Product Feedback",
                display_order=1, created_by=superadmin_id, created_date=now)
    s21 = insert(cursor, "survey_section", page_id=p2, title="Features",
                 display_order=0, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s21, type="MULTI_CHOICE",
           title="Which features do you use most? (select all that apply)",
           options='{"options":[{"key":"tickets","label":"Ticket Management"},{"key":"surveys","label":"Surveys"},{"key":"kb","label":"Knowledge Base"},{"key":"reports","label":"Reports"},{"key":"notifications","label":"Notifications"}]}',
           required=1, display_order=0, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s21, type="RATING", title="How satisfied are you with our product features?",
           options='{"max":5}', required=1, display_order=1, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s21, type="TEXT", title="What feature would you like to see next?",
           options=None, required=0, display_order=2, created_by=superadmin_id, created_date=now)

    # ── Template 2: IT Support Feedback ──
    t2 = insert(cursor, "survey_template",
                tenant_id=None,
                title="IT Support Feedback",
                description="Let us know how your recent IT support experience went.",
                status="PUBLISHED",
                version=1,
                allow_resubmit=0,
                created_by=superadmin_id,
                created_date=now,
                last_modified_date=now)
    template_ids.append(t2)

    p3 = insert(cursor, "survey_page", template_id=t2, title="Support Quality",
                display_order=0, created_by=superadmin_id, created_date=now)
    s31 = insert(cursor, "survey_section", page_id=p3, title="Agent Evaluation",
                 display_order=0, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s31, type="RATING", title="How knowledgeable was the support agent?",
           options='{"max":5}', required=1, display_order=0, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s31, type="RATING", title="How would you rate the response time?",
           options='{"max":5}', required=1, display_order=1, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s31, type="SINGLE_CHOICE",
           title="Was your issue resolved?",
           options='{"options":[{"key":"yes","label":"Yes, fully resolved"},{"key":"partial","label":"Partially resolved"},{"key":"no","label":"Not resolved"}]}',
           required=1, display_order=2, created_by=superadmin_id, created_date=now)
    insert(cursor, "survey_question", section_id=s31, type="TEXTAREA",
           title="Additional comments about your support experience:",
           options=None, required=0, display_order=3, created_by=superadmin_id, created_date=now)

    print(f"  ✓ Created {len(template_ids)} survey templates (with pages, sections, questions)")

# ── Tickets ────────────────────────────────────────────────────────

TICKET_TITLES = [
    "Unable to log in after password reset",
    "Page crashes when uploading large files",
    "Dashboard charts not rendering correctly",
    "Email notifications not being received",
    "API returning 500 error intermittently",
    "Need access to production logs",
    "Invoice generator producing incorrect totals",
    "User profile image upload fails on mobile",
    "Search functionality returns no results",
    "Export to CSV timing out for large datasets",
    "Two-factor authentication setup not working",
    "Slow page load on ticket list view",
    "Webhook delivery failing for certain events",
    "Custom field values not saving",
    "Permission denied when accessing reports",
    "Unable to change email address in settings",
    "Integration with Jira broken after update",
    "Duplicate tickets being created",
    "Notification spam — receiving too many emails",
    "Language switch not persisting across sessions",
    "PDF attachment preview not loading",
    "Cannot assign ticket to specific agent",
    "Account locked after single failed attempt",
    "Date picker widget broken in Safari",
    "Keyboard shortcuts not working in ticket editor",
]

TICKET_DESCRIPTIONS = [
    "## Steps to Reproduce\n1. Go to login page\n2. Click 'Forgot Password'\n3. Follow the reset link\n4. Attempt to login with new password\n\n## Expected\nShould be able to login\n\n## Actual\n'Invalid credentials' error",
    "When I try to upload a file larger than 50MB, the page freezes and the browser console shows a 413 error. This worked last week.",
    "The dashboard charts are showing blank spaces. Console shows: `Error: Cannot read property 'length' of undefined`. Started after today's deployment.",
    "I haven't received any email notifications for the past 3 days. Checked spam folder — nothing there. Other system emails (password reset) work fine.",
    "GET /api/tickets?status=OPEN returns 500 about 30% of the time. Seems to happen under load. Stack trace attached.",
    "I need access to the production log files to debug an issue. My current role doesn't have the required permissions.",
    "The invoice generated for order #12345 shows a total of $1,234.56 but it should be $1,198.00. Tax calculation seems off.",
    "On iOS Safari and Chrome, the profile image upload button doesn't respond to tap. Works fine on Android and desktop.",
    "Searching for 'deployment' returns 0 results even though there are hundreds of tickets with that word in the title.",
    "When exporting more than 10,000 tickets to CSV, the request times out after 60 seconds. Need a way to export in batches.",
    "I followed the 2FA setup wizard but the QR code never appears. Tried on Chrome and Firefox, same result.",
    "The ticket list page takes 8-10 seconds to load when I have more than 500 tickets. Pagination doesn't help.",
    "Webhooks for the 'ticket.updated' event stopped firing yesterday. Delivery logs show 403 errors from our endpoint.",
    "I added a custom field 'Department' to tickets, but the value is not being saved when creating or editing tickets.",
    "When I go to Reports → Agent Performance, I get 'Access Denied' even though I'm a team lead.",
    "Settings → Profile → Change Email accepts the new email but doesn't actually update it. Old email still shows.",
    "The Jira integration was working fine before the v2.3 update. Now tickets created in Jira don't sync back.",
    "When I submit a ticket, sometimes two identical tickets get created. Happens about 1 out of 10 times.",
    "I'm getting 50+ notification emails per day. Need a way to digest or reduce the frequency.",
    "I switched the UI language to French but it reverts to English whenever I navigate to a different page.",
    "The PDF attachment preview shows a spinner indefinitely. The file downloads fine when I click 'Download'.",
    "I'm an admin but I don't see the 'Assign' dropdown on the ticket detail page. The HTML select element is missing.",
    "My account got locked after just one failed login attempt. The lockout threshold should be higher.",
    "The date picker calendar doesn't open when clicking the date field in Safari 17. Works in Chrome and Firefox.",
    "Ctrl+Enter to submit a reply doesn't work anymore. Also, Ctrl+B for bold and Ctrl+I for italic are broken.",
]

def batch_insert(cursor, table, columns, rows):
    """
    Batch insert using multi-row VALUES syntax.
    columns: list of column names, e.g. ['col1', 'col2']
    rows: list of value tuples, e.g. [(1, 'a'), (2, 'b')]
    Returns the first auto-increment ID.
    """
    if not rows:
        return None
    placeholders = ", ".join(["(" + ", ".join(["%s"] * len(cols)) + ")" for cols in rows])
    flat_values = [v for row in rows for v in row]
    col_names = ", ".join(columns)
    sql = f"INSERT INTO {table} ({col_names}) VALUES {placeholders}"
    cursor.execute(sql, flat_values)
    return cursor.lastrowid


def create_tickets(cursor, tenant_id, tenant_users, num_tickets):
    """
    Generate random tickets for one tenant using batch inserts.
    tenant_users: { 'admin': id, 'agents': [ids], 'users': [ids] }
    """
    all_agents = tenant_users["agents"]
    all_users = tenant_users["users"]
    admin_id = tenant_users["admin"]
    if not all_agents:
        return

    all_user_ids = all_users + [admin_id]
    BATCH = 500

    REPLY_CONTENTS = [
        "Thank you for reporting this. I'm looking into it now.",
        "I was able to reproduce the issue. Working on a fix.",
        "Could you provide more details about your environment?",
        "This has been escalated to the development team.",
        "The fix has been deployed. Please verify on your end.",
        "Closing this ticket as the issue is resolved. Feel free to reopen if needed.",
        "I've assigned this to the infrastructure team for further investigation.",
        "Update: we've identified the root cause. Fix will be in the next release.",
        "*Internal note:* This is related to the database migration from last week.",
        "*Internal note:* Customer has a high-priority SLA — expedite the fix.",
    ]

    # ── Phase 1: generate ticket rows + per-ticket reply data ──
    ticket_rows = []
    replies_by_ticket = []  # list of lists: replies_by_ticket[ti] = [reply_tuple, ...]
    reply_cols = ["tenant_id", "ticket_id", "user_id", "content",
                   "is_internal", "is_edited", "created_by", "created_date",
                   "last_modified_date"]

    for ti in range(num_tickets):
        created_by = random.choice(all_user_ids)
        status = random.choice(STATUSES)
        priority = random.choice(PRIORITIES)
        assigned_to = random.choice(all_agents) if status != "OPEN" else (
            random.choice(all_agents) if random.random() > 0.3 else None
        )
        created_offset = -random.randint(60, 60 * 24 * 30) * 60

        ticket_rows.append((
            tenant_id,
            random.choice(TICKET_TITLES),
            random.choice(TICKET_DESCRIPTIONS),
            status,
            priority,
            random.choice(CATEGORIES),
            assigned_to,
            ts(created_offset + random.randint(3600, 86400)) if status in ("RESOLVED", "CLOSED") else None,
            ts(created_offset + random.randint(86400, 172800)) if status == "CLOSED" else None,
            created_by,
            ts(created_offset),
            ts(created_offset + random.randint(600, 3600)),
        ))

        # Generate reply data for this ticket (ticket_id placeholder = 0)
        ticket_replies = []
        num_replies = random.randint(1, 4)
        for ri in range(num_replies):
            is_internal = 1 if random.random() < 0.15 else 0
            reply_offset = created_offset + (ri + 1) * random.randint(300, 3600)
            reply_by = random.choice([assigned_to, created_by, admin_id] + all_agents)
            reply_by = next((u for u in [reply_by] if u is not None), admin_id)
            ticket_replies.append((
                tenant_id,
                0,  # placeholder — patched after ticket insert
                reply_by,
                random.choice(REPLY_CONTENTS),
                is_internal,
                0,
                reply_by,
                ts(reply_offset),
                ts(reply_offset) if is_internal else None,
            ))
        replies_by_ticket.append(ticket_replies)

    # ── Phase 2: batch insert tickets ──
    ticket_cols = [
        "tenant_id", "title", "description", "status", "priority",
        "category", "assigned_to", "resolved_date", "closed_date",
        "created_by", "created_date", "last_modified_date",
    ]
    first_ticket_id = None
    for batch_start in range(0, len(ticket_rows), BATCH):
        batch = ticket_rows[batch_start:batch_start + BATCH]
        fid = batch_insert(cursor, "ticket", ticket_cols, batch)
        if first_ticket_id is None:
            first_ticket_id = fid

    # ── Phase 3: patch reply ticket_ids & batch insert ──
    if first_ticket_id is None:
        return 0

    all_reply_rows = []
    for ti in range(num_tickets):
        tid = first_ticket_id + ti
        for reply in replies_by_ticket[ti]:
            # Patch ticket_id (index 1) from placeholder 0 → real tid
            patched = list(reply)
            patched[1] = tid
            all_reply_rows.append(tuple(patched))

    for batch_start in range(0, len(all_reply_rows), BATCH):
        batch = all_reply_rows[batch_start:batch_start + BATCH]
        batch_insert(cursor, "ticket_reply", reply_cols, batch)

    return num_tickets


# ── Main ───────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Seed the ticket-system database with multi-tenant test data.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
        Examples:
          python seed_db.py
          python seed_db.py --tenants 5 --agents 3 --users 6 --tickets 50
          python seed_db.py --host 192.168.1.100 --user admin --password secret --database prod_test
        """))
    p.add_argument("--host", default=CONFIG["host"])
    p.add_argument("--port", type=int, default=CONFIG["port"])
    p.add_argument("--user", default=CONFIG["user"])
    p.add_argument("--password", default=CONFIG["password"])
    p.add_argument("--database", default=CONFIG["database"])
    p.add_argument("--tenants", type=int, default=CONFIG["num_tenants"])
    p.add_argument("--agents", type=int, default=CONFIG["agents_per_tenant"],
                   help="agents per tenant (default: %(default)s)")
    p.add_argument("--users", type=int, default=CONFIG["users_per_tenant"],
                   help="regular users per tenant (default: %(default)s)")
    p.add_argument("--tickets", type=int, default=CONFIG["tickets_per_tenant"],
                   help="tickets per tenant (default: %(default)s)")
    p.add_argument("--no-confirm", action="store_true",
                   help="skip confirmation prompt (for scripting)")
    return p.parse_args()


def main(args):
    try:
        import pymysql
    except ImportError:
        print("Error: pymysql is not installed.")
        print("Run: pip install pymysql")
        sys.exit(1)

    print("=" * 60)
    print("  Ticket System — Database Seed Script")
    print("=" * 60)
    print(f"  Host:     {args.host}:{args.port}")
    print(f"  Database: {args.database}")
    print(f"  Tenants:  {args.tenants}")
    print(f"  Per tenant: 1 admin + {args.agents} agents + {args.users} users")
    print(f"  Tickets per tenant: {args.tickets}")
    print(f"  Total users:  {(1 + args.agents + args.users) * args.tenants}")
    print(f"  Total tickets: {args.tenants * args.tickets}")
    print("=" * 60)

    if not args.no_confirm:
        ok = input("\n⚠ This will DELETE ALL existing data. Continue? [y/N] ")
        if ok.strip().lower() != "y":
            print("Aborted.")
            sys.exit(0)

    conn = pymysql.connect(
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password,
        database=args.database,
        charset="utf8mb4",
    )
    conn.begin()
    cursor = conn.cursor()

    try:
        print("\n[1/6] Clearing all data...")
        clear_all(cursor)

        print("\n[2/6] Creating tenants...")
        tenant_ids = create_tenants(cursor, args.tenants)

        print("\n[3/6] Creating users...")
        superadmin = create_superadmin(cursor)
        all_tenant_users = {}
        total_users = 0
        for tid in tenant_ids:
            tu = create_users_for_tenant(cursor, tid, f"{tid:02d}", args.agents, args.users)
            all_tenant_users[tid] = tu
            total_users += 1 + args.agents + args.users
        print(f"  ✓ Total users created: {total_users} (+ superadmin)")

        print("\n[4/6] Creating system default configs (under superadmin)...")
        create_reply_templates(cursor, superadmin)
        create_knowledge_articles(cursor, superadmin)
        create_sla_configs(cursor, superadmin, tenant_ids)
        create_survey_templates(cursor, superadmin)

        print("\n[5/6] Creating tickets (with replies)...")
        total_tickets = 0
        for i, tid in enumerate(tenant_ids):
            label = f"tenant-{tid:02d}"
            print(f"  Generating tickets for {label} ({args.tickets} tickets)...", end=" ", flush=True)
            count = create_tickets(cursor, tid, all_tenant_users[tid], args.tickets)
            total_tickets += count
            print("✓")
        print(f"  ✓ Total tickets created: {total_tickets}")

        print("\n[6/6] Committing...")
        conn.commit()
        print("  ✓ All changes committed.")

    except Exception as e:
        conn.rollback()
        print(f"\n✗ Error: {e}")
        sys.exit(1)
    finally:
        cursor.close()
        conn.close()

    # ── Summary ──
    print("\n" + "=" * 60)
    print("  Seed Complete!")
    print("=" * 60)
    print(f"""
    Superadmin:
      Username: superadmin
      Password: Admin@123
      Role:     ROLE_ADMIN (tenant_id=NULL)

    Per Tenant (x{args.tenants}):
      Admin:  admin{{N}}       / Admin@123
      Agents: agent{{N}}-1..{{M}} / Agent@123   (x{args.agents})
      Users:  user{{N}}-1..{{K}}  / User@123    (x{args.users})
      Tickets: {args.tickets} tickets with replies

    Connection:
      mysql -u {args.user} -p{args.password} {args.database}
    """)
    print("=" * 60)


if __name__ == "__main__":
    # Parse args first so --help works without pymysql installed
    args = parse_args()
    main(args)
